### ISSUE TITLE
no progress after syncRequired (tutorial, first step)

### ISSUE THREAD

**Issue by DanielRuf** [proophboard/node-cody-server#1]
I have tested on Chrome and Firefox, in both browsers I get stuck at this stage (with Node 16.19.0):

![grafik](https://user-images.githubusercontent.com/827205/227516178-99643705-1a14-4b81-9cca-097005867408.png)

![grafik](https://user-images.githubusercontent.com/827205/227516315-6f95a321-6764-4f00-8733-1dcabb92955e.png)

The browser console contains these entries:

![grafik](https://user-images.githubusercontent.com/827205/227516565-683a0f2f-a107-48db-a550-0588e6aabcda.png)

Is there maybe something missing in the documentation at https://wiki.prooph-board.com/cody/nodejs-cody-tutorial?

**Comment by DanielRuf** [comment]
Please move the issue to https://github.com/proophboard/ts-cody-tutorial/issues

**Comment by codeliner** [comment]
Bug in free client has been fixed. See linked issue https://github.com/proophboard/php-cody-tutorial/issues/2
thx again for reporting
